apiVersion : apps/v1
kind: Deployment
metadata:
  name : spring
spec:
  selector:
    matchLabels:
      app : spring-mysql
  template:
    metadata:
      labels:
        app : spring-mysql
    spec:
      containers:
        - name: spring-db
          image: aryan2311023/spring_mysql:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MY_SQL_ENDPOINT
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name : spring-svc
spec:
  type: ClusterIP
  selector:
    app : spring-mysql
  ports:
    - port: 8080
      targetPort: 8080
